[2024-09-21T10:24:55.485+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:19:52.857911+00:00 [queued]>
[2024-09-21T10:24:55.494+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:19:52.857911+00:00 [queued]>
[2024-09-21T10:24:55.494+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:24:55.494+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 2
[2024-09-21T10:24:55.494+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2024-09-21T10:24:55.502+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_table_vk> on 2024-09-21 10:19:52.857911+00:00
[2024-09-21T10:24:55.504+0000] {standard_task_runner.py:55} INFO - Started process 4449 to run task
[2024-09-21T10:24:55.507+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_saver_v01', 'create_table_vk', 'manual__2024-09-21T10:19:52.857911+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dag_saver.py', '--cfg-path', '/tmp/tmpq5_na3rd']
[2024-09-21T10:24:55.507+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask create_table_vk
[2024-09-21T10:24:55.548+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_saver_v01.create_table_vk manual__2024-09-21T10:19:52.857911+00:00 [running]> on host 16da3808dee2
[2024-09-21T10:24:55.590+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=<NAME>
AIRFLOW_CTX_DAG_ID=dag_saver_v01
AIRFLOW_CTX_TASK_ID=create_table_vk
AIRFLOW_CTX_EXECUTION_DATE=2024-09-21T10:19:52.857911+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-09-21T10:19:52.857911+00:00
[2024-09-21T10:24:55.591+0000] {sql.py:253} INFO - Executing: 
            create table if not exists vk_group_posts (
                id serial PRIMARY KEY,
                vk_group_link VARCHAR,
                vk_post_id INTEGER,
                vk_post_text VARCHAR,
                vk_post_comments VARCHAR,
                datetime timestamp default systimestemp
            )
        
[2024-09-21T10:24:55.603+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-09-21T10:24:55.718+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2024-09-21T10:24:55.725+0000] {sql.py:364} INFO - Running statement: 
            create table if not exists vk_group_posts (
                id serial PRIMARY KEY,
                vk_group_link VARCHAR,
                vk_post_id INTEGER,
                vk_post_text VARCHAR,
                vk_post_comments VARCHAR,
                datetime timestamp default systimestemp
            )
        , parameters: None
[2024-09-21T10:24:55.730+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.FeatureNotSupported: cannot use column reference in DEFAULT expression
LINE 8:                 datetime timestamp default systimestemp
                                                   ^

[2024-09-21T10:24:55.735+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=dag_saver_v01, task_id=create_table_vk, execution_date=20240921T101952, start_date=20240921T102455, end_date=20240921T102455
[2024-09-21T10:24:55.741+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task create_table_vk (cannot use column reference in DEFAULT expression
LINE 8:                 datetime timestamp default systimestemp
                                                   ^
; 4449)
[2024-09-21T10:24:55.769+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2024-09-21T10:24:55.785+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
